(in-package #:cl-dataflow.test)

(eval-when (:load-toplevel :execute)
  (dolist (test-file '("core-runtime-example-test.lisp"
                        "core-runtime-protocol-test.lisp"
                        "core-runtime-graph-test.lisp"))
    (%load-fragment test-file)))

(define-public-api-contract-test public-api-exports-match-documentation
  "CL-DATAFLOW"
  (:classes
    (cl-dataflow-error
      invalid-input-error
      graph-error
      node-not-found-error
      graph-cycle-error
      effect-handler-missing-error
      invalid-transition-error
      guard-failed-error
      node
      edge
      graph
      context
      event
      effect
      state-transition
      state-machine
      pipeline)
    :macros
    (define-state-machine
      define-pipeline
      define-workflow
      with-effect-handler-scope))
  (:errors
    cl-dataflow-error
    invalid-input-error
    invalid-input-expected
    invalid-input-value
    invalid-input-detail
    graph-error
    graph-error-graph
    graph-error-detail
    node-not-found-error
    node-not-found-designator
    graph-cycle-error
    graph-cycle-nodes
    effect-handler-missing-error
    missing-effect-type
    effect-handler-missing-effect
    effect-handler-missing-detail
    invalid-transition-error
    invalid-transition-detail
    invalid-transition-state
    invalid-transition-event-type
    guard-failed-error
    guard-failed-detail
    guard-failed-state
    guard-failed-event-type
    guard-failed-transition)
  (:node
    node
    node-p
    node-name
    node-inputs
    node-outputs
    node-handler
    node-metadata
    make-node)
  (:edge
    edge
    edge-p
    edge-from
    edge-from-port
    edge-to
    edge-to-port
    edge-metadata
    make-edge)
  (:graph
    graph
    graph-p
    graph-nodes
    graph-edges
    graph-metadata
    make-graph
    copy-graph
    add-node
    add-edge
    find-node
    graph-source-nodes
    graph-sink-nodes
    graph-reachable-p
    graph-descendants
    graph-ancestors
    graph-path
    validate-graph
    topological-sort)
  (:graph-algorithms
    graph-node-names
    graph-order
    graph-size
    graph-empty-p
    graph-successors
    graph-predecessors
    graph-out-degree
    graph-in-degree
    graph-transpose
    graph-acyclic-p
    graph-strongly-connected-components
    graph-connected-components
    graph-topological-generations
    graph-distance
    graph->dot
    graph->mermaid
    graph-to-plist
    plist-to-graph
    remove-node
    remove-edge
    graph-subgraph
    graph-merge
    graph-relabel-node)
  (:context
    context
    context-p
    context-values
    context-events
    context-events-in-order
    context-event-types
    context-events-of-type
    context-effects
    context-effects-in-order
    context-effect-types
    context-effects-of-type
    context-trace
    context-trace-in-order
    context-last-event
    context-last-effect
    context-value
    context-node-values
    context-metadata
    context-effect-handlers
    context-result
    context-state
    make-context
    copy-context
    context-summary
    format-trace
    trace-summary)
  (:event
    event
    event-p
    event-type
    event-payload
    event-metadata
    event-trace-index
    make-event
    emit-event
    copy-event)
  (:effect
    effect
    effect-p
    effect-type
    effect-payload
    effect-metadata
    effect-trace-index
    effect-result
    make-effect
    perform-effect
    copy-effect
    register-effect-handler
    context-effect-handler
    effect-handled-p
    context-effect-handler-types
    with-effect-handler-scope)
  (:state-machine
    state-transition
    state-transition-p
    transition-from
    transition-event-type
    transition-to
    transition-guard
    transition-action
    transition-metadata
    make-transition
    define-state-machine
    state-machine
    state-machine-p
    state-machine-state
    state-machine-initial-state
    state-machine-transitions
    state-machine-history
    state-machine-metadata
    make-state-machine
    copy-state-machine
    reset-state-machine
    state-machine-last-transition
    state-machine-available-transitions
    state-machine-can-step-p
    step-state-machine
    run-state-machine
    run-state-machine-with-context
    make-state-machine-node
    state-machine-states
    state-machine-event-types
    state-machine-reachable-states
    state-machine-unreachable-states
    state-machine-terminal-states
    state-machine-deterministic-p
    state-machine->dot
    state-machine->mermaid
    state-machine-run-states
    state-machine-accepts-p
    state-machine-event-path)
  (:pipeline
    pipeline
    pipeline-p
    pipeline-graph
    pipeline-stages
    pipeline-metadata
    make-pipeline
    define-pipeline
    define-workflow
    copy-pipeline
    run-pipeline
    run-pipeline-with-context
    run-pipeline-sequence
    pipeline->dot
    pipeline->mermaid
    pipeline-node-names
    pipeline-stage-names
    pipeline-source-names
    pipeline-sink-names)
  (:combinators
    mapping-handler
    compose-handlers
    retrying-handler
    fallback-handler
    memoizing-handler
    tapping-handler
    wrap-node
    node-with-retry
    node-with-fallback
    node-with-memoization
    node-with-tap)
  (:protocols
    flow-name
    flow-metadata
    flow-kind)
  (:streams
    flow-stream-p
    empty-stream
    list->stream
    stream-of
    stream-range
    stream-map
    stream-filter
    stream-scan
    stream-take
    stream-drop
    stream-take-while
    stream-drop-while
    stream-distinct
    stream-flat-map
    stream-concat
    stream-zip
    stream-tap
    stream-collect
    stream-reduce
    stream-for-each
    stream-count
    stream-first
    stream-empty-p
    stream-iterate
    stream-repeat
    stream-cycle
    stream-enumerate
    stream-unfold
    stream-chunk
    stream-window
    stream-partition-by
    stream-sum
    stream-min
    stream-max
    stream-find
    stream-some
    stream-every
    stream-last
    stream-nth)
  (:testing
    run-pipeline-with-test-context
    assert-emitted-events
    assert-performed-effects
    assert-final-state
    assert-state-machine-state
    assert-pipeline-result))
