(in-package #:cl-dataflow.test)

(deftest internal-output-binding-helpers-normalize-node-results
  (let ((silent (make-node "silent" :outputs '()))
        (disconnected (make-node "disconnected"))
        (single (make-node "single" :outputs '("value")))
        (multi (make-node "multi" :outputs '("left" "right"))))
    (setf (slot-value disconnected 'cl-dataflow::outputs) nil)
    (is (equal (cl-dataflow::%node-output-bindings disconnected 42)
               '()))
    (is (equal (cl-dataflow::%node-output-bindings silent 42)
               '(("value" . 42))))
    (is (equal (cl-dataflow::%node-output-bindings single 42)
               '(("value" . 42))))
    (is (equal (cl-dataflow::%node-output-bindings single '(("value" . 42)))
               '(("value" . 42))))
    (is (equal (cl-dataflow::%node-output-bindings multi '(:left 1 :right 2))
               '(("LEFT" . 1) ("RIGHT" . 2))))))

(deftest internal-collect-node-inputs-prefers-edges-and-falls-back-to-structured-input
  (let* ((graph (make-graph))
         (source (make-node "source" :outputs '("left" "right")))
         (single-sink (make-node "single-sink"))
         (join (make-node "join" :inputs '("left" "right")))
         (context (make-context)))
    (dolist (node (list source single-sink join))
      (add-node graph node))
    (add-edge graph source single-sink :from-port "left")
    (add-edge graph source join :from-port "left" :to-port "left")
    (add-edge graph source join :from-port "right" :to-port "right")
    (cl-dataflow::%store-value context (node-name source) "left" 10)
    (cl-dataflow::%store-value context (node-name source) "right" 20)
    (is (= (cl-dataflow::%collect-node-inputs context graph single-sink :ignored)
           10))
    (is (equal (cl-dataflow::%collect-node-inputs context graph join :ignored)
               (list (cons "left" 10)
                     (cons "right" 20)))))
  (let ((standalone-graph (make-graph))
        (standalone (make-node "standalone" :inputs '("left" "right"))))
    (add-node standalone-graph standalone)
    (is (equal (cl-dataflow::%collect-node-inputs (make-context)
                                                  standalone-graph
                                                  standalone
                                                  (list :left 1 :right 2))
               (list (cons "LEFT" 1)
                     (cons "RIGHT" 2))))))

(deftest internal-collect-sink-results-collapses-single-and-branching-sinks
  (let* ((graph (make-graph))
         (source (make-node "source" :outputs '("left" "right")))
         (left (make-node "left"))
         (right (make-node "right"))
         (context (make-context)))
    (dolist (node (list source left right))
      (add-node graph node))
    (add-edge graph source left :from-port "left")
    (add-edge graph source right :from-port "right")
    (cl-dataflow::%store-value context (node-name left) "value" 16)
    (cl-dataflow::%store-value context (node-name right) "value" 30)
    (is (equal (cl-dataflow::%collect-sink-results graph
                                                   context
                                                   (topological-sort graph))
               '(("left" ("value" . 16))
                 ("right" ("value" . 30))))))
  (let* ((graph (make-graph))
         (sink (make-node "sink" :outputs '("left" "right")))
         (context (make-context)))
    (add-node graph sink)
    (cl-dataflow::%store-value context (node-name sink) "left" 6)
    (cl-dataflow::%store-value context (node-name sink) "right" 10)
    (is (equal (cl-dataflow::%collect-sink-results graph
                                                   context
                                                   (topological-sort graph))
               '(("left" . 6) ("right" . 10)))))
  (let* ((graph (make-graph))
         (sink (make-node "sink"))
         (context (make-context)))
    (add-node graph sink)
    (cl-dataflow::%store-value context (node-name sink) "value" 16)
    (is (= (cl-dataflow::%collect-sink-results graph
                                               context
                                               (topological-sort graph))
           16))))

(deftest internal-collect-sink-results-return-nil-without-execution-order
  (let* ((graph (make-graph))
         (context (make-context)))
    (is (null (cl-dataflow::%collect-sink-results graph context '())))))

(deftest internal-normalization-helpers-cover-scalar-plist-and-table-paths
  (with-test-table (table "value" 10 "other" 20)
    (let ((public-copy (cl-dataflow::%copy-structured-value table)))
      (setf (gethash "value" public-copy) 99)
      (is (= (gethash "value" table) 10)))
    (is (equal (cl-dataflow::%normalize-name :state) "STATE"))
    (is (equal (cl-dataflow::%normalize-name 42) "42"))
    (is (equal (cl-dataflow::%normalize-port-list :value) '("VALUE")))
    (is (= (cl-dataflow::%plist-value '("value" 1 "other" 2) "other") 2))
    (is (null (cl-dataflow::%plist-value '("value" 1) "missing")))
    (is (= (cl-dataflow::%normalize-structured-input table '("value")) 10))
    (is (equal (cl-dataflow::%normalize-structured-input '("value" 1 "other" 2)
                                                         '("value"))
               1))
    (is (equal (cl-dataflow::%normalize-output-structure 7 nil) 7))
    (is (equal (cl-dataflow::%normalize-output-structure 7 '("value"))
               '(("value" . 7))))
    (is (equal (cl-dataflow::%hash-table-keys table)
               '("value" "other")))))

(deftest internal-error-copy-helpers-copy-nested-model-structures
  (let* ((node (make-node "source"
                          :inputs '("in")
                          :outputs '("out")
                          :metadata '((:kind :stage))))
         (edge (make-edge "source" "sink"
                          :from-port "out"
                          :to-port "in"
                          :metadata '((:kind :edge))))
         (graph (make-graph :metadata '((:kind :graph)))))
    (add-node graph node)
    (setf (graph-edges graph) (list edge))
    (let* ((graph-copy (cl-dataflow::%copy-error-value graph))
           (copied-node (gethash "source" (slot-value graph-copy 'cl-dataflow::nodes)))
           (copied-edge (first (slot-value graph-copy 'cl-dataflow::edges))))
      (is (not (eq graph-copy graph)))
      (is (not (eq copied-node node)))
      (is (not (eq copied-edge edge)))
      (setf (node-inputs copied-node) '("mutated")
            (node-metadata copied-node) '((:kind :mutated))
            (edge-metadata copied-edge) '((:kind :mutated)))
      (is (equal (node-inputs node) '("in")))
      (is (equal (node-metadata node) '((:kind :stage))))
      (is (equal (edge-metadata edge) '((:kind :edge))))
      (is (equal (graph-metadata graph) '((:kind :graph)))))))
