(in-package #:cl-dataflow.test)

(deftest protocol-generics-expose-public-flow-introspection
  (let* ((node (make-node 'source :metadata '((:kind :stage))))
         (edge (make-edge 'source 'sink :metadata '((:kind :edge))))
         (graph (make-graph :metadata '((:kind :graph))))
         (context (make-context :metadata '((:kind :context))))
         (event (make-event "boot" :metadata '((:kind :event))))
         (effect (make-effect "audit" :metadata '((:kind :effect))))
         (transition (make-transition "idle" "start" "running"
                                      :metadata '((:kind :transition))))
         (machine (make-state-machine :state "idle"
                                      :metadata '((:kind :machine))))
         (pipeline (make-pipeline :metadata '((:kind :pipeline)))))
    (is (equal (flow-name node) "SOURCE"))
    (is (equal (flow-name edge) '("SOURCE" "SINK")))
    (is (equal (flow-name graph) :graph))
    (is (equal (flow-name context) :context))
    (is (equal (flow-name event) "boot"))
    (is (equal (flow-name effect) "audit"))
    (is (equal (flow-name transition) "start"))
    (is (equal (flow-name machine) "idle"))
    (is (equal (flow-name pipeline) :pipeline))
    (is (equal (flow-kind node) :node))
    (is (equal (flow-kind edge) :edge))
    (is (equal (flow-kind graph) :graph))
    (is (equal (flow-kind context) :context))
    (is (equal (flow-kind event) :event))
    (is (equal (flow-kind effect) :effect))
    (is (equal (flow-kind transition) :state-transition))
    (is (equal (flow-kind machine) :state-machine))
    (is (equal (flow-kind pipeline) :pipeline))
    (is (equal (flow-metadata node) '((:kind :stage))))
    (is (equal (flow-metadata edge) '((:kind :edge))))
    (is (equal (flow-metadata graph) '((:kind :graph))))
    (is (equal (flow-metadata context) '((:kind :context))))
    (is (equal (flow-metadata event) '((:kind :event))))
    (is (equal (flow-metadata effect) '((:kind :effect))))
    (is (equal (flow-metadata transition) '((:kind :transition))))
    (is (equal (flow-metadata machine) '((:kind :machine))))
    (is (equal (flow-metadata pipeline) '((:kind :pipeline))))))

(deftest protocol-generics-return-independent-metadata-snapshots
  (let* ((graph (make-graph :metadata '((:kind :graph))))
         (context (make-context :metadata '((:kind :context))))
         (machine (make-state-machine :state "idle"
                                      :metadata '((:kind :machine))))
         (pipeline (make-pipeline :metadata '((:kind :pipeline))))
         (graph-metadata (flow-metadata graph))
         (context-metadata (flow-metadata context))
         (machine-metadata (flow-metadata machine))
         (pipeline-metadata (flow-metadata pipeline)))
    (setf (cadr (first graph-metadata)) :mutated
          (cadr (first context-metadata)) :mutated
          (cadr (first machine-metadata)) :mutated
          (cadr (first pipeline-metadata)) :mutated)
    (is (equal (flow-metadata graph) '((:kind :graph))))
    (is (equal (flow-metadata context) '((:kind :context))))
    (is (equal (flow-metadata machine) '((:kind :machine))))
    (is (equal (flow-metadata pipeline) '((:kind :pipeline))))))

(deftest protocol-generics-reject-non-flow-values
  (dolist (reader (list #'flow-name #'flow-kind #'flow-metadata))
    (signals type-error
      (funcall reader 42))))

(deftest graph-readers-return-independent-snapshots
  (let* ((graph (make-graph))
         (source (make-node "source" :metadata '((:kind :stage))))
         (sink (make-node "sink" :metadata '((:kind :stage))))
         (edge (make-edge "source" "sink" :metadata '((:kind :edge))))
         (values (make-test-table "count" (list 1 2)))
         (context (make-context :values values)))
    (add-node graph source)
    (add-node graph sink)
    (setf (graph-edges graph) (list edge))
    (let ((nodes-snapshot (graph-nodes graph))
          (edges-snapshot (graph-edges graph))
          (sources-snapshot (graph-source-nodes graph))
          (sinks-snapshot (graph-sink-nodes graph))
          (values-snapshot (context-values context)))
      (is (not (eq (gethash "source" nodes-snapshot) (find-node graph "source"))))
      (is (not (eq (gethash "sink" nodes-snapshot) (find-node graph "sink"))))
      (is (not (eq (first edges-snapshot) (first (graph-edges graph)))))
      (is (not (eq sources-snapshot (graph-source-nodes graph))))
      (is (not (eq sinks-snapshot (graph-sink-nodes graph))))
      (setf (node-metadata (gethash "source" nodes-snapshot)) '((:kind :mutated))
            (edge-metadata (first edges-snapshot)) '((:kind :mutated)))
      (setf (gethash "mutated" nodes-snapshot) (make-node "mutated")
            (gethash "count" values-snapshot) (list 3 4)
            (car sources-snapshot) (make-node "mutated-source")
            (car sinks-snapshot) (make-node "mutated-sink"))
      (push (make-edge "source" "mutated") edges-snapshot)
      (is (= (hash-table-count (graph-nodes graph)) 2))
      (is (= (hash-table-count nodes-snapshot) 3))
      (is (= (length (graph-edges graph)) 1))
      (is (= (length edges-snapshot) 2))
      (is (equal (mapcar #'node-name (graph-source-nodes graph))
                 '("source")))
      (is (equal (mapcar #'node-name (graph-sink-nodes graph))
                 '("sink")))
      (is (equal (node-metadata (find-node graph "source"))
                 '((:kind :stage))))
      (is (equal (edge-metadata (first (graph-edges graph)))
                 '((:kind :edge))))
      (is (equal (gethash "count" (context-values context)) '(1 2)))
      (is (equal (gethash "count" values-snapshot) '(3 4))))))
