(defpackage #:cl-dataflow
  (:use #:cl)
  (:export
    #:cl-dataflow-error
    #:invalid-input-error
    #:invalid-input-expected
    #:invalid-input-value
    #:invalid-input-detail
    #:graph-error
    #:graph-error-graph
    #:graph-error-detail
    #:node-not-found-error
    #:node-not-found-designator
    #:graph-cycle-error
    #:graph-cycle-nodes
    #:effect-handler-missing-error
    #:missing-effect-type
    #:effect-handler-missing-effect
    #:effect-handler-missing-detail
    #:invalid-transition-error
    #:invalid-transition-detail
    #:invalid-transition-state
    #:invalid-transition-event-type
    #:guard-failed-error
    #:guard-failed-detail
    #:guard-failed-state
    #:guard-failed-event-type
    #:guard-failed-transition

    #:node
    #:node-p
    #:node-name
    #:node-inputs
    #:node-outputs
    #:node-handler
    #:node-metadata
    #:make-node

    #:edge
    #:edge-p
    #:edge-from
    #:edge-from-port
    #:edge-to
    #:edge-to-port
    #:edge-metadata
    #:make-edge

    #:graph
    #:graph-p
    #:graph-nodes
    #:graph-edges
    #:graph-metadata
    #:make-graph
    #:copy-graph
    #:copy-context
    #:copy-event
    #:copy-effect
    #:add-node
    #:add-edge
    #:find-node
    #:graph-source-nodes
    #:graph-sink-nodes
    #:graph-reachable-p
    #:graph-descendants
    #:graph-ancestors
    #:graph-path
    #:validate-graph
    #:topological-sort
    #:graph-node-names
    #:graph-order
    #:graph-size
    #:graph-empty-p
    #:graph-successors
    #:graph-predecessors
    #:graph-out-degree
    #:graph-in-degree
    #:graph-transpose
    #:graph-acyclic-p
    #:graph-strongly-connected-components
    #:graph-connected-components
    #:graph-topological-generations
    #:graph-distance
    #:graph->dot
    #:graph->mermaid
    #:graph-layout
    #:graph-to-plist
    #:plist-to-graph
    #:remove-node
    #:remove-edge
    #:graph-subgraph
    #:graph-merge
    #:graph-relabel-node
    #:graph-contract-edge
    #:graph-transitive-closure
    #:graph-transitive-reduction
    #:graph-topological-rank
    #:graph-longest-path
    #:graph-all-paths
    #:graph-find-cycle
    #:graph-weighted-distance
    #:graph-weighted-path
    #:graph-density
    #:graph-degree-histogram
    #:graph-bipartite-p
    #:graph-greedy-coloring
    #:graph-equal-p
    #:graph-undirected-reachable-p
    #:graph-connected-p
    #:graph-strongly-connected-p
    #:graph-self-loop-nodes
    #:graph-condensation
    #:graph-distances-from
    #:graph-bfs-order
    #:graph-dfs-order
    #:graph-eccentricity
    #:graph-diameter
    #:graph-closeness-centrality
    #:graph-union
    #:graph-intersection
    #:graph-difference
    #:graph-filter-nodes
    #:graph-map-nodes
    #:graph-diff
    #:graph-articulation-points
    #:graph-bridges

    #:context
    #:context-p
    #:context-values
    #:context-events
    #:context-events-in-order
    #:context-event-types
    #:context-events-of-type
    #:context-effects
    #:context-effects-in-order
    #:context-effect-types
    #:context-effects-of-type
    #:context-trace
    #:context-trace-in-order
    #:context-last-event
    #:context-last-effect
    #:context-value
    #:context-node-values
    #:context-metadata
    #:context-effect-handlers
    #:context-result
    #:context-state
    #:make-context
    #:context-summary
    #:format-trace
    #:trace-summary
    #:context-merge
    #:context-trace-of-kind
    #:context-to-plist
    #:plist-to-context
    #:context-equal-p

    #:event
    #:event-p
    #:event-type
    #:event-payload
    #:event-metadata
    #:event-trace-index
    #:make-event
    #:emit-event
    #:emit-events
    #:event-of-type-p
    #:event-to-plist
    #:plist-to-event

    #:effect
    #:effect-p
    #:effect-type
    #:effect-payload
    #:effect-metadata
    #:effect-trace-index
    #:effect-result
    #:make-effect
    #:perform-effect
    #:register-effect-handler
    #:context-effect-handler
    #:effect-handled-p
    #:context-effect-handler-types
    #:with-effect-handler-scope
    #:perform-effects
    #:context-effect-results
    #:context-effect-results-of-type
    #:effect-of-type-p
    #:effect-to-plist
    #:plist-to-effect

    #:state-transition
    #:state-transition-p
    #:transition-from
    #:transition-event-type
    #:transition-to
    #:transition-guard
    #:transition-action
    #:transition-metadata
    #:make-transition
    #:define-state-machine

    #:state-machine
    #:state-machine-p
    #:state-machine-state
    #:state-machine-initial-state
    #:state-machine-transitions
    #:state-machine-history
    #:state-machine-metadata
    #:make-state-machine
    #:copy-state-machine
    #:reset-state-machine
    #:state-machine-last-transition
    #:state-machine-available-transitions
    #:state-machine-can-step-p
    #:step-state-machine
    #:run-state-machine
    #:run-state-machine-with-context
    #:make-state-machine-node
    #:state-machine-states
    #:state-machine-event-types
    #:state-machine-reachable-states
    #:state-machine-unreachable-states
    #:state-machine-terminal-states
    #:state-machine-deterministic-p
    #:state-machine->dot
    #:state-machine->mermaid
    #:state-machine-run-states
    #:state-machine-accepts-p
    #:state-machine-event-path
    #:state-machine-to-plist
    #:plist-to-state-machine
    #:state-machine-complete-p
    #:state-machine-transition-for
    #:add-transition
    #:remove-transition
    #:state-machine-relabel-state
    #:state-machine->graph
    #:state-machine-equal-p
    #:state-machine-reachable-p

    #:pipeline
    #:pipeline-p
    #:pipeline-graph
    #:pipeline-stages
    #:pipeline-metadata
    #:make-pipeline
    #:define-pipeline
    #:define-workflow
    #:copy-pipeline
    #:run-pipeline
    #:run-pipeline-with-context
    #:run-pipeline-sequence
    #:pipeline->dot
    #:pipeline->mermaid
    #:pipeline-node-names
    #:pipeline-stage-names
    #:pipeline-source-names
    #:pipeline-sink-names
    #:pipeline-to-plist
    #:plist-to-pipeline
    #:pipeline-validate
    #:pipeline-stage-count
    #:map-pipeline
    #:pipeline->node
    #:pipeline-equal-p
    #:run-pipeline-times
    #:run-pipeline-until-fixpoint
    #:run-pipeline-while

    #:mapping-handler
    #:compose-handlers
    #:retrying-handler
    #:fallback-handler
    #:memoizing-handler
    #:tapping-handler
    #:wrap-node
    #:node-with-retry
    #:node-with-fallback
    #:node-with-memoization
    #:node-with-tap
    #:contract-handler
    #:node-with-contract

    #:flow-name
    #:flow-metadata
    #:flow-kind
    #:flow-describe
    #:flow-children

    #:make-subject
    #:subject-p
    #:subject-subscribe
    #:subject-unsubscribe
    #:subject-emit
    #:subject-subscriber-count
    #:subject-map
    #:subject-filter
    #:subject-merge
    #:subject-collect
    #:subject-scan
    #:subject-distinct
    #:subject-tap
    #:subject-take
    #:subject-zip
    #:subject-combine-latest
    #:subject-buffer
    #:subject-drop
    #:subject-take-while
    #:subject-drop-while
    #:subject-count
    #:subject-flat-map
    #:subject-partition

    #:flow-stream-p
    #:empty-stream
    #:list->stream
    #:stream-of
    #:stream-range
    #:stream-map
    #:stream-filter
    #:stream-scan
    #:stream-take
    #:stream-drop
    #:stream-take-while
    #:stream-drop-while
    #:stream-distinct
    #:stream-flat-map
    #:stream-concat
    #:stream-zip
    #:stream-tap
    #:stream-collect
    #:stream-reduce
    #:stream-for-each
    #:stream-count
    #:stream-first
    #:stream-empty-p
    #:stream-iterate
    #:stream-repeat
    #:stream-cycle
    #:stream-enumerate
    #:stream-unfold
    #:stream-chunk
    #:stream-window
    #:stream-partition-by
    #:stream-sum
    #:stream-min
    #:stream-max
    #:stream-find
    #:stream-some
    #:stream-every
    #:stream-last
    #:stream-nth
    #:stream-zip-with
    #:stream-interleave
    #:stream-take-nth
    #:stream-dedupe-consecutive
    #:stream-interpose
    #:stream-group-by
    #:stream-frequencies
    #:stream-index-by
    #:stream-partition
    #:stream-split-at
    #:stream-average
    #:stream-distinct-by
    #:stream-flatten
    #:stream-scan1
    #:stream-count-if
    #:stream-variance
    #:stream-stddev
    #:stream-median
    #:stream-find-index
    #:stream-none-p
    #:stream-mode
    #:stream-cartesian

    #:run-pipeline-with-test-context
    #:assert-emitted-events
    #:assert-performed-effects
    #:assert-final-state
    #:assert-state-machine-state
    #:assert-pipeline-result))

(in-package #:cl-dataflow)

(defmacro %load-fragment (pathname)
  (let ((source-directory
          (make-pathname :name nil
                          :type nil
                          :defaults (or *compile-file-pathname*
                                        *load-truename*))))
    `(eval-when (:compile-toplevel :load-toplevel :execute)
        (load (merge-pathnames ,pathname ,source-directory)))))
