(in-package #:cl-dataflow)

;;;; Extended stream vocabulary layered on the FLOW-STREAM core in streams.lisp:
;;;; generators (finite and infinite), windowing/grouping operators, and eager
;;;; aggregate consumers. Generators stay lazy so an infinite source is safe as
;;;; long as a bounded consumer (STREAM-TAKE, STREAM-NTH, STREAM-FIND, ...) drives
;;;; it; every consumer here iterates rather than recurses.

;;; --- Generators ----------------------------------------------------------

(defun stream-iterate (function seed)
  "Return the infinite stream SEED, (FUNCTION SEED), (FUNCTION (FUNCTION SEED)), ..."
  (%make-flow-stream
   (lambda ()
     (cons seed (stream-iterate function (funcall function seed))))))

(defun stream-repeat (value)
  "Return the infinite stream that yields VALUE forever."
  (%make-flow-stream
   (lambda ()
     (cons value (stream-repeat value)))))

(defun %stream-cycle-from (remaining full)
  (%make-flow-stream
   (lambda ()
     (if (null remaining)
         (%stream-step (%stream-cycle-from full full))
         (cons (first remaining) (%stream-cycle-from (rest remaining) full))))))

(defun stream-cycle (list)
  "Return the infinite stream that yields the elements of LIST in order, repeating.
An empty LIST yields the empty stream."
  (if (null list)
      (empty-stream)
      (%stream-cycle-from list list)))

(defun %stream-enumerate-from (stream index)
  (%make-flow-stream
   (lambda ()
     (let ((step (%stream-step stream)))
       (if (eq step :end)
           :end
           (cons (cons index (car step))
                 (%stream-enumerate-from (cdr step) (1+ index))))))))

(defun stream-enumerate (stream &key (start 0))
  "Return a stream of (INDEX . ELEMENT) conses over STREAM, indices counting up
from START."
  (%stream-enumerate-from stream start))

(defun stream-unfold (function seed)
  "Return the stream generated by repeatedly applying FUNCTION to a seed. FUNCTION
returns NIL to stop, or (VALUE . NEXT-SEED) to emit VALUE and continue from
NEXT-SEED."
  (%make-flow-stream
   (lambda ()
     (let ((result (funcall function seed)))
       (if result
           (cons (car result) (stream-unfold function (cdr result)))
           :end)))))

;;; --- Windowing and grouping ----------------------------------------------

(defun %positive-size (size caller)
  (when (< size 1)
    (error 'invalid-input-error
           :expected 'positive-integer
           :value size
           :detail (format nil "~A size must be positive." caller)))
  size)

(defun %stream-chunk (n stream)
  (%make-flow-stream
   (lambda ()
     (let ((chunk '())
           (current stream)
           (count 0))
       (loop
         (when (= count n) (return))
         (let ((step (%stream-step current)))
           (when (eq step :end) (return))
           (push (car step) chunk)
           (setf current (cdr step))
           (incf count)))
       (if chunk
           (cons (nreverse chunk) (%stream-chunk n current))
           :end)))))

(defun stream-chunk (n stream)
  "Return a stream of lists, each holding up to N consecutive elements of STREAM
(the final list may be shorter). N must be positive."
  (%positive-size n "STREAM-CHUNK")
  (%stream-chunk n stream))

(defun %stream-window (n stream)
  (%make-flow-stream
   (lambda ()
     (let ((window (stream-collect (stream-take n stream))))
       (if (= (length window) n)
           (cons window (%stream-window n (stream-drop 1 stream)))
           :end)))))

(defun stream-window (n stream)
  "Return a stream of the length-N sliding windows of STREAM (each a list),
advancing one element at a time. A stream shorter than N yields no windows. N must
be positive."
  (%positive-size n "STREAM-WINDOW")
  (%stream-window n stream))

(defun stream-partition-by (function stream)
  "Return a stream of lists grouping each maximal run of consecutive elements of
STREAM that share the same (FUNCALL FUNCTION ELEMENT) key (compared with EQUAL)."
  (%make-flow-stream
   (lambda ()
     (let ((step (%stream-step stream)))
       (if (eq step :end)
           :end
           (let ((key (funcall function (car step)))
                 (group (list (car step)))
                 (current (cdr step)))
             (loop
               (let ((next (%stream-step current)))
                 (when (eq next :end) (return))
                 (unless (equal (funcall function (car next)) key) (return))
                 (push (car next) group)
                 (setf current (cdr next))))
             (cons (nreverse group)
                   (stream-partition-by function current))))))))

;;; --- Aggregate consumers -------------------------------------------------

(defun stream-sum (stream &key (key #'identity))
  "Return the sum of (FUNCALL KEY ELEMENT) over STREAM (0 for an empty stream)."
  (stream-reduce (lambda (accumulator element)
                   (+ accumulator (funcall key element)))
                 0 stream))

(defun %stream-extreme (stream key compare default)
  (let ((current stream)
        (best-element default)
        (best-key nil)
        (found nil))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end)
          (return best-element))
        (let ((candidate-key (funcall key (car step))))
          (when (or (not found) (funcall compare candidate-key best-key))
            (setf best-element (car step)
                  best-key candidate-key
                  found t)))
        (setf current (cdr step))))))

(defun stream-min (stream &key (key #'identity) default)
  "Return the element of STREAM with the smallest (FUNCALL KEY ELEMENT), or DEFAULT
when STREAM is empty."
  (%stream-extreme stream key #'< default))

(defun stream-max (stream &key (key #'identity) default)
  "Return the element of STREAM with the largest (FUNCALL KEY ELEMENT), or DEFAULT
when STREAM is empty."
  (%stream-extreme stream key #'> default))

(defun stream-find (predicate stream &optional default)
  "Return the first element of STREAM satisfying PREDICATE, or DEFAULT if none do."
  (let ((current stream))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end) (return default))
        (when (funcall predicate (car step)) (return (car step)))
        (setf current (cdr step))))))

(defun stream-some (predicate stream)
  "Return the first non-NIL (FUNCALL PREDICATE ELEMENT) over STREAM, or NIL."
  (let ((current stream))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end) (return nil))
        (let ((value (funcall predicate (car step))))
          (when value (return value)))
        (setf current (cdr step))))))

(defun stream-every (predicate stream)
  "Return true when every element of STREAM satisfies PREDICATE (true for empty)."
  (let ((current stream))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end) (return t))
        (unless (funcall predicate (car step)) (return nil))
        (setf current (cdr step))))))

(defun stream-last (stream &optional default)
  "Return the last element of STREAM, or DEFAULT when STREAM is empty."
  (let ((current stream)
        (result default))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end) (return result))
        (setf result (car step)
              current (cdr step))))))

(defun stream-nth (n stream &optional default)
  "Return the Nth element (0-based) of STREAM, or DEFAULT when STREAM has fewer than
N+1 elements."
  (let ((current stream)
        (remaining n))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end) (return default))
        (when (<= remaining 0) (return (car step)))
        (decf remaining)
        (setf current (cdr step))))))
