(in-package #:cl-dataflow)

;;;; Extended stream vocabulary layered on the FLOW-STREAM core in streams.lisp:
;;;; generators (finite and infinite), windowing/grouping operators, and eager
;;;; aggregate consumers. Generators stay lazy so an infinite source is safe as
;;;; long as a bounded consumer (STREAM-TAKE, STREAM-NTH, STREAM-FIND, ...) drives
;;;; it; every consumer here iterates rather than recurses.

;;; --- Generators ----------------------------------------------------------

(defun stream-iterate (function seed)
  "Return the infinite stream SEED, (FUNCTION SEED), (FUNCTION (FUNCTION SEED)), ..."
  (%make-flow-stream
   (lambda ()
     (cons seed (stream-iterate function (funcall function seed))))))

(defun stream-repeat (value)
  "Return the infinite stream that yields VALUE forever."
  (%make-flow-stream
   (lambda ()
     (cons value (stream-repeat value)))))

(defun %stream-cycle-from (remaining full)
  (%make-flow-stream
   (lambda ()
     (if (null remaining)
         (%stream-step (%stream-cycle-from full full))
         (cons (first remaining) (%stream-cycle-from (rest remaining) full))))))

(defun stream-cycle (list)
  "Return the infinite stream that yields the elements of LIST in order, repeating.
An empty LIST yields the empty stream."
  (if (null list)
      (empty-stream)
      (%stream-cycle-from list list)))

(defun %stream-enumerate-from (stream index)
  (%make-flow-stream
   (lambda ()
     (let ((step (%stream-step stream)))
       (if (eq step :end)
           :end
           (cons (cons index (car step))
                 (%stream-enumerate-from (cdr step) (1+ index))))))))

(defun stream-enumerate (stream &key (start 0))
  "Return a stream of (INDEX . ELEMENT) conses over STREAM, indices counting up
from START."
  (%stream-enumerate-from stream start))

(defun stream-unfold (function seed)
  "Return the stream generated by repeatedly applying FUNCTION to a seed. FUNCTION
returns NIL to stop, or (VALUE . NEXT-SEED) to emit VALUE and continue from
NEXT-SEED."
  (%make-flow-stream
   (lambda ()
     (let ((result (funcall function seed)))
       (if result
           (cons (car result) (stream-unfold function (cdr result)))
           :end)))))

;;; --- Windowing and grouping ----------------------------------------------

(defun %positive-size (size caller)
  (when (< size 1)
    (error 'invalid-input-error
           :expected 'positive-integer
           :value size
           :detail (format nil "~A size must be positive." caller)))
  size)

(defun %stream-chunk (n stream)
  (%make-flow-stream
   (lambda ()
     (let ((chunk '())
           (current stream)
           (count 0))
       (loop
         (when (= count n) (return))
         (let ((step (%stream-step current)))
           (when (eq step :end) (return))
           (push (car step) chunk)
           (setf current (cdr step))
           (incf count)))
       (if chunk
           (cons (nreverse chunk) (%stream-chunk n current))
           :end)))))

(defun stream-chunk (n stream)
  "Return a stream of lists, each holding up to N consecutive elements of STREAM
(the final list may be shorter). N must be positive."
  (%positive-size n "STREAM-CHUNK")
  (%stream-chunk n stream))

(defun %stream-window-fill (n stream)
  (let ((window '())
        (current stream)
        (count 0))
    (loop
      (when (= count n) (return))
      (let ((step (%stream-step current)))
        (when (eq step :end) (return))
        (push (car step) window)
        (setf current (cdr step))
        (incf count)))
    (values (nreverse window) current count)))

(defun %stream-window-state->list (front rear)
  (if rear
      (append front (reverse rear))
      (copy-list front)))

(defun %stream-window-advance (front rear value)
  (let ((next-front (rest front))
        (next-rear (cons value rear)))
    (if next-front
        (values next-front next-rear)
        (values (reverse next-rear) '()))))

(defun %stream-window-next (front rear rest-stream)
  (%make-flow-stream
   (lambda ()
     (let ((step (%stream-step rest-stream)))
       (if (eq step :end)
           :end
           (multiple-value-bind (next-front next-rear)
               (%stream-window-advance front rear (car step))
             (%stream-step
              (%stream-window-from next-front next-rear (cdr step)))))))))

(defun %stream-window-from (front rear rest-stream)
  (%make-flow-stream
   (lambda ()
     (cons (%stream-window-state->list front rear)
           (%stream-window-next front rear rest-stream)))))

(defun %stream-window (n stream)
  (%make-flow-stream
   (lambda ()
     (multiple-value-bind (window rest-stream count)
         (%stream-window-fill n stream)
       (if (= count n)
           (%stream-step (%stream-window-from window '() rest-stream))
           :end)))))

(defun stream-window (n stream)
  "Return a stream of the length-N sliding windows of STREAM (each a list),
advancing one element at a time. A stream shorter than N yields no windows. N must
be positive."
  (%positive-size n "STREAM-WINDOW")
  (%stream-window n stream))

(defun stream-partition-by (function stream)
  "Return a stream of lists grouping each maximal run of consecutive elements of
STREAM that share the same (FUNCALL FUNCTION ELEMENT) key (compared with EQUAL)."
  (%make-flow-stream
   (lambda ()
     (let ((step (%stream-step stream)))
       (if (eq step :end)
           :end
           (let ((key (funcall function (car step)))
                 (group (list (car step)))
                 (current (cdr step)))
             (loop
               (let ((next (%stream-step current)))
                 (when (eq next :end) (return))
                 (unless (equal (funcall function (car next)) key) (return))
                 (push (car next) group)
                 (setf current (cdr next))))
             (cons (nreverse group)
                   (stream-partition-by function current))))))))

;;; --- Aggregate consumers -------------------------------------------------

(defun stream-sum (stream &key (key #'identity) limit)
  "Return the sum of (FUNCALL KEY ELEMENT) over STREAM (0 for an empty stream).
LIMIT bounds the number of input elements accepted."
  (%validate-stream-limit limit "STREAM-SUM")
  (let ((accumulator 0))
    (do-stream (element stream :limit limit :caller "STREAM-SUM" :on-end accumulator)
      (incf accumulator (funcall key element)))))

(defun %stream-extreme (stream key compare default limit caller)
  (%validate-stream-limit limit caller)
  (let ((best-element default)
        (best-key nil)
        (found nil))
    (do-stream (element stream :limit limit :caller caller :on-end best-element)
      (let ((candidate-key (funcall key element)))
        (when (or (not found) (funcall compare candidate-key best-key))
          (setf best-element element
                best-key candidate-key
                found t))))))

(defun stream-min (stream &key (key #'identity) default limit)
  "Return the element of STREAM with the smallest (FUNCALL KEY ELEMENT), or DEFAULT
when STREAM is empty. LIMIT bounds the number of input elements accepted."
  (%stream-extreme stream key #'< default limit "STREAM-MIN"))

(defun stream-max (stream &key (key #'identity) default limit)
  "Return the element of STREAM with the largest (FUNCALL KEY ELEMENT), or DEFAULT
when STREAM is empty. LIMIT bounds the number of input elements accepted."
  (%stream-extreme stream key #'> default limit "STREAM-MAX"))

(defun %parse-stream-default-limit-options (options caller)
  (labels ((invalid-options ()
             (error 'invalid-input-error
                    :expected '(default &key limit)
                    :value options
                    :detail (format nil "~A accepts at most DEFAULT and :LIMIT."
                                    caller))))
    (cond
      ((null options) (values nil nil))
      ((eq (first options) :limit)
       (unless (= (length options) 2)
         (invalid-options))
       (values nil (second options)))
      (t
       (let ((default (first options))
             (keyword-options (rest options)))
         (cond
           ((null keyword-options) (values default nil))
           ((and (= (length keyword-options) 2)
                 (eq (first keyword-options) :limit))
            (values default (second keyword-options)))
           (t (invalid-options))))))))

(defun stream-find (predicate stream &rest options)
  "Return the first element of STREAM satisfying PREDICATE, or DEFAULT if none do.
LIMIT bounds the number of input elements accepted."
  (multiple-value-bind (default limit)
      (%parse-stream-default-limit-options options "STREAM-FIND")
    (%validate-stream-limit limit "STREAM-FIND")
    (do-stream (element stream :limit limit :caller "STREAM-FIND" :on-end default)
      (when (funcall predicate element) (return element)))))

(defun stream-some (predicate stream &key limit)
  "Return the first non-NIL (FUNCALL PREDICATE ELEMENT) over STREAM, or NIL.
LIMIT bounds the number of input elements accepted."
  (%validate-stream-limit limit "STREAM-SOME")
  (do-stream (element stream :limit limit :caller "STREAM-SOME" :on-end nil)
    (let ((value (funcall predicate element)))
      (when value (return value)))))

(defun stream-every (predicate stream &key limit)
  "Return true when every element of STREAM satisfies PREDICATE (true for empty).
LIMIT bounds the number of input elements accepted."
  (%validate-stream-limit limit "STREAM-EVERY")
  (do-stream (element stream :limit limit :caller "STREAM-EVERY" :on-end t)
    (unless (funcall predicate element) (return nil))))

(defun stream-last (stream &rest options)
  "Return the last element of STREAM, or DEFAULT when STREAM is empty.
LIMIT bounds the number of input elements accepted."
  (multiple-value-bind (default limit)
      (%parse-stream-default-limit-options options "STREAM-LAST")
    (%validate-stream-limit limit "STREAM-LAST")
    (let ((result default))
      (do-stream (element stream :limit limit :caller "STREAM-LAST" :on-end result)
        (setf result element)))))

(defun stream-nth (n stream &optional default)
  "Return the Nth element (0-based) of STREAM, or DEFAULT when STREAM has fewer than
N+1 elements."
  (let ((current stream)
        (remaining n))
    (loop
      (let ((step (%stream-step current)))
        (when (eq step :end) (return default))
        (when (<= remaining 0) (return (car step)))
        (decf remaining)
        (setf current (cdr step))))))
